dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -H "X-JFrog-Art-Api:AKCp8mZcgvMbr8gdeT1tXiamfEdHB4CjaAFzfMDYbKPysESTrHxpYGauQ2nvv9yRs2TkkuZpc" -T hw01-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb "https://slp17.jfrog.io/artifactory/hw-generic-local/hw01-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
